library(scilitlearn)
setwd('~/R/scilitlearn/')
wos = load_data('sample.tsv')
year_count(wos)
top_authors(wos)
title_words(wos)
title_bigrams(wos)  
title_bigrams_separated(wos)  
title_bigrams_filtered(wos)  
title_bigrams_count(wos) 
keywords(wos)
keyword_count(wos)  
cited_references_gather(wos)  
cited_reference_count(wos)  
